# Generated by Django 5.2.7 on 2025-10-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tehran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100000)),
                ('Room', models.CharField()),
                ('Parking', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=4)),
                ('Warehouse', models.CharField(max_length=10)),
            ],
        ),
    ]
