# Generated by Django 5.2.7 on 2025-10-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehran',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Parking',
            field=models.BooleanField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Warehouse',
            field=models.CharField(),
        ),
    ]
