# Generated by Django 5.2.7 on 2025-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehran', '0002_alter_tehran_address_alter_tehran_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehran',
            name='Elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Parking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Warehouse',
            field=models.BooleanField(),
        ),
    ]
