# Generated by Django 5.2.7 on 2025-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehran', '0003_tehran_elevator_alter_tehran_parking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehran',
            name='Area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tehran',
            name='Warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
